= Angular 學習指南

== 目錄

* link:Introduction.html[簡介]
* link:Installation.html[安裝前置作業]
* link:CLI_Commands.html[常用指令與 CLI 指南]
* link:Project_Setup.html[專案建立與啟動]
* link:Directory_Structure.html[目錄結構介紹]
* link:Component_Structure.html[元件結構詳解]

= Angular

== 簡介
**Angular** 是一個基於 **TypeScript** 的開源前端框架，由 **Google** 開發，用於構建 Web 應用程式。包含以下內容：

* **一個元件化的框架** +
* **一整套深思熟慮整合出的函式庫**，提供路由機制、表單管理、Client/Server 通訊等功能 +
* **一組完善的開發工具**，幫助開發、建置、測試、更新程式碼

link:index.html[回首頁]

== 安裝前置作業

在本地端開發 Angular 應用程式前，您需要安裝：

* **Node.js** +
Angular 需要 **Node.js** 的最新版本或 **LTS** 版本進行開發。 +
可以在 CMD 中輸入 `node -v` 檢查安裝是否成功。 +
https://nodejs.org/zh-tw/download/prebuilt-installer[Node.js 下載]

* **npm 套件管理器** +
Angular、Angular CLI 和應用程式依賴 **npm** 套件管理器進行管理。 +
**npm** 是 **Node.js** 的套件管理工具，與 **Node.js** 一同安裝。 +
可以在 CMD 中輸入 `npm -v` 檢查安裝是否成功。

* **安裝Anguler**
+
----
npm install -g @angular/cli
----

* **建立專案**
+
----
ng new project-name
----

* **啟動應用程式**
+
----
cd project-name
ng serve --open
----
+
[quote]
____
預設網域通常為http://localhost:4200/
____

link:index.html[回首頁]

== 常用指令
安裝完成後，可以使用 `ng` 命令來建立、建置、測試和啟動 Angular 應用程式。

[cols="1,3", options="header"]
|===
| 命令 | 描述

| https://angular.dev/cli/build[`ng build --prod`]
| **編譯 Angular 專案為生產環境版本，包含優化與縮小檔案大小**

| https://angular.dev/cli/serve[`ng serve --open`]
| **建構應用程式並啟動開發伺服器，並自動在瀏覽器中開啟應用程式**

| https://angular.dev/cli/generate#component-command[`ng generate component my-component`]
| **生成一個新的元件 `my-component`**

| https://angular.dev/cli/test[`ng test --watch=false`]
| **執行單元測試並在測試完成後退出**

| https://angular.dev/cli/e2e[`ng e2e --protractor-config=e2e/protractor.conf.js`]
| **使用指定的 Protractor 配置檔案執行端到端測試**
|===

=== 補充: Protractor
**Protractor** 是一個專為 **Angular** 設計的端到端測試框架，基於 **Selenium WebDriver**。

=== 補充: Selenium WebDriver
**Selenium WebDriver** 是一個自動化網頁應用測試工具，允許透過程式控制瀏覽器來執行與使用者相似的操作。

=== 補充: 端到端測試
**端到端測試**模擬真實用戶操作，確保應用程式的整體功能正常運作。

link:index.html[回首頁]

== Angular 專案目錄結構

[source,shell]
----
my-app/
├── e2e/ <1>
├── node_modules/ <2>
├── src/ <3>
│   ├── app/ <4>
│   │   ├── app.component.html <5>
│   │   ├── app.component.ts <6>
│   │   ├── app.module.ts <7>
│   │   └── app.component.css <8>
│   ├── assets/ <9>
│   ├── environments/ <10>
│   ├── index.html <11>
│   ├── main.ts <12>
│   ├── polyfills.ts <13>
│   ├── styles.css <14>
│   └── ...
├── .editorconfig <15>
├── .gitignore <16>
├── angular.json <17>
├── package.json <18>
├── tsconfig.json <19>
├── tslint.json <20>
└── ...
----

== 專案結構說明

=== 專案設定檔

[width=75%, cols="1,4"]
|===
|.editorconfig |用來設定統一的程式碼風格
|.gitignore |設定git檔案的忽略清單
|angular.json |用來配置Angular CLI 所需的設定，定義專案中的應用程式、測試、建置過程和不同環境的設定
|package.json |用來配置專案所需要使用的依賴套件
|package-lock.json |用來鎖定依賴項的版本號，確保其他人使用npm install時版本可以保持一致
|src/ |應用程式源碼區
|public/ | 用來放置一些可公開的靜態資源
|node_modules/ |存放專案所有的依賴套件
|tsconfig.json |用來設定TypeScript的配置
|===

=== 應用程式原始碼檔案
放置在src下的檔案

[width=75%, cols="1,4"]
|===
|app/ |包含定義應用程式邏輯和資料的元件檔案
|index.html |預設html主頁面。Angular CLI會自動將專案內的JavaScript和CSS引入到裡面
|main.ts |執行應用程式的進入點
|styles.css |全域的CSS配置
|===

放置在src/app下的檔案
[width=75%, cols="1,4"]
|===
|app.config.ts |用來告訴Angular該如何組裝和啟動應用程式的配置，當有需要新增更多providers時應該要設置在此
|app.component.ts |應用程式的核心組件與關連的view都會設定在這裡，也就是AppComponent，任何屬性以及事件都會寫在這裡
|app.component.html |定義與AppComponent關聯的HTML
|app.component.css |定義AppComponent的樣式
|app.component.spec.ts |定義AppComponent的單元測試
|app.routes.ts |定義應用程式的路由配置
|===

=== 應用程式設定檔
[width=75%, cols="1,4"]
|===
|tsconfig.app.json |用來設定特定應用程式的TypeScript配置
|tsconfig.spec.json |用來設定應用程式測試的TypeScript配置
|===

== 熟悉你的 Angular 程式

本教學導覽主要使用的程式原始檔在 `src/app` 資料夾內。由 CLI 自動產生的主要檔案如下：

- `app.module.ts`: 列出此專案使用的所有檔案。此檔案在專案中扮演中央樞紐的角色。
- `app.component.ts`: 又被稱為元件類別，內含此專案主要頁面的相關邏輯。
- `app.component.html`: 內含 AppComponent 所使用的網頁 html，作為元件模板（Template）。
- `app.component.css`: 內含 AppComponent 裡面的樣式，讓樣式定義只影響特定模組。

Angular 的元件由三部分構成：模板、樣式、類別。例如，`app.component.ts`、`app.component.html`、以及 `app.component.css` 一同構成 AppComponent。

== Angular 專案結構
**Angular** 基於 **TypeScript** 開發，應用程式由 **元件 (Component)** 組成。 +
每個元件包含 **HTML 模板**、**CSS 樣式**和帶有 `@Component()` 裝飾器的 **TypeScript 類別**。

=== HTML模板 (Template)
Angular 組件的模板文件，負責定義類別組件的視圖結構，透過 Angular 的模板語法實現資料的顯示、條件渲染、事件處理等功能，並動態更新畫面，與 app.component.ts 當中的邏輯緊密結合，實現互動式的使用者界面。

==== HTML模板常用的語法

- 插值表達式 {{}}: 用來顯示組件類中的資料

*app.component.ts*

[source,typescript]
----
 export class AppComponent {
  title = 'test-app';
  userName = 'John';
}
----

*app.component.html*

[source,html]
----
<h1>{{ title }}</h1>  <!--  test-app   -->
<p>Hello, {{ userName }}!</p>  <!--  Hello, John   -->
----

- 屬性綁定: [property]="componentAttribute"

將組件中的資料綁定到HTML元素的屬性上，讓屬性值可以動態更新

*app.component.ts*

[source,typescript]
----
export class AppComponent {
  title = 'test-app';
  color = "color: #26b72a";
}
----

*app.component.html*

[source,html]
----
<p [style]="color">{{ title }}</p>
----

- 事件綁定:

當操作者觸發某個事件（點擊、鍵盤事件）時，綁定的函數會被調用

*app.component.ts*

[source,typescript]
----
export class AppComponent {
  title = 'test-app';
  color = "color: #26b72a";

  onClick() {
    this.color = "color: #000000";
  }
}
----

*app.component.html*

[source,html]
----
<p [style]="color">{{ title }}</p>
<button (click)="onClick()">點擊切換成黑色</button>
----


- 雙向資料綁定: [(ngModel)]="property"

雙向資料綁定允許模型與視圖之間的資料同步。當模型變更時，視圖自動更新，當使用者在視圖中修改時，模型也會自動變更

*app.component.ts*

[source,typescript]
----
export class AppComponent {
  title = 'test-app';
  color = "color: #26b72a";

  userName = '';
}
----

*app.component.html*

[source,html]
----
<p [style]="color">{{ title }}</p>
<input [(ngModel)]="userName" placeholder="Enter your name">
<p>Hello, {{ userName }}!</p>
----

上述程式當使用者在輸入框輸入內容時，網頁同時會動態更新userName屬性

- 條件渲染: *ngIf

根據條件來顯示或隱藏 HTML 元素

*app.component.ts*

[source,typescript]
----
export class AppComponent {
  title = 'test-app';
  color = "color: #26b72a";

  isLoggedIn = false;
  userName = 'John';

  onClick() {
    if (this.isLoggedIn) {
      this.isLoggedIn = false
    } else {
      this.isLoggedIn = true
    }
  }
}
----

*app.component.html*

[source,html]
----
<p [style]="color">{{ title }}</p>
<button (click)="onClick()">切換登入</button>

<p *ngIf="isLoggedIn">Welcome back, {{ userName }}!</p>
<p *ngIf="!isLoggedIn">Please log in.</p>
----

- 迭代渲染: *ngFor

用來來迭代一個陣列，並渲染每個項目

*app.component.ts*

[source,typescript]
----
export class AppComponent {
  title = 'test-app';
  color = "color: #26b72a";

  persons = ['John', 'Jeff', 'Iris'];
}
----

*app.component.html*
[source,html]
----
<p [style]="color">{{ title }}</p>
<ul>
  <li *ngFor="let person of persons">{{ person }}</li>
</ul>
----


=== CSS樣式 (Style)
在Angular中的樣式組件是用來為特定的組件設計樣式

==== :host & :host-context

. :host
+
    - :host是Angular提供的特殊選擇器，用來定義宿主元素(也就是index.html當中的<app-root>)的樣式
+   
*簡單範例:*
+
*css*
+
----
:host {
    display: block;
    margin: 10px;
    padding: 20px;
    background-color: lightblue;
}
----
+
*html*
+
----
<body>
  <app-root></app-root>
</body>
----
+
若selector屬性為app-root，上述的<app-root>標籤就會套用到:host的樣式

. host-context
+
- :host-context 選擇器用來根據組件的外部上下文環境來設置樣式，當組件的祖先元素（或父元素）滿足特定條件時，該選擇器可以應用樣式到組件本身或其內部元素
+
*簡單範例*: 當使用者選擇了黑暗模式，所有的元件都應該要改成黑色背景白色文字 
+
*css*
+
[source,css]
----
/* child.component.css */
:host-context(.dark-theme) {
  background-color: black;
  color: white;
}
----
+
*html*
+
[source,html]
----
<div class="dark-theme">
  <app-child></app-child>
</div>
----
+
:host-context(.dark-theme) 會檢查 app-child 的父級元素或祖先元素是否有 .dark-theme 類，如果有則會應用這些樣式，將 app-child 的背景設置為黑色，文字顏色設置為白色





=== 類別 (Class)
類別裡面包含了元件的相關邏輯，例如資料處理、事件處理等。 +
類別會放在 `app.component.ts` 檔案裡，而 `app` 就是元件的名稱。 +
當建立一個元件時，他會帶有 `@Component()` 裝飾器，裡面會有檔案的路徑指向，告訴Angular要去哪裡找HTML模板和CSS樣式。 +
一個元件的基本寫法如下：

[source,typescript]
----
import { Component } from "@angular/core";

@Component({
    selector: "app-item",
    // 接下來的檔案路徑會指出其它檔案在什麼位置
    templateUrl: "./item.component.html",
    styleUrls: ["./item.component.css"],
})
export class ItemComponent {
    // 程式碼寫在這裡
}
----

這個元件被稱為 `ItemComponent`，他的選擇器是 `app-item` 。 +
選擇器就像是HTML的標籤，可以把他放到其他的模板裡。 +
當瀏覽器渲染到選擇器時，就會把這個元件的HTML模板和CSS樣式一起渲染出來。

Angular 的元件具備高度封裝性，讓專案結構看起來更直覺。 +
而 Angular 的元件也讓專案更易於做單元測試、讓程式碼更易於解讀。

==== Component類別簡單範例

- 定義屬性:

[source,typescript]
----
export class AppComponent {
  title = 'test-app';
}
----

定義了組件的屬性，在html中可使用{{ title }}來取得組件的屬性值

[source,html]
----
<p>{{ title }}</p>  <!-- 在頁面上會輸出test-app -->
----

- 定義方法:

[source,typescript]
----
export class AppComponent {
  title = 'app-root';
  userName = 'John';
  isLoggedIn = false;

  // 變更使用者登入狀態
  toggleLoginStatus() {
    this.isLoggedIn = !this.isLoggedIn;
  }

  // 設定新的使用者名稱
  changeUserName(newName: string) {
    this.userName = newName;
  }
}
----

在HTML中綁定這些方法來實現按鈕點擊事件

[source,html]
----
<h1>{{ title }}</h1>
<p>User: {{ userName }}</p>
<button (click)="toggleLoginStatus()">
  {{ isLoggedIn ? 'Logout' : 'Login' }}
</button>
----

- 定義組件的生命週期:

[source,typescript]
----
export class AppComponent implements OnInit, OnDestroy {
  title = 'test-app';
  data: any;

  ngOnInit() {
    // 初始化，通常用來取得資料
    console.log('Component initialized');
    this.data = this.fetchData();
  }

  ngOnDestroy() {
    // 當組件銷毀時執行
    console.log('Component destroyed');
  }

  fetchData() {
    return { message: 'I love systex' };
  }
}
----

==== Angular怎麼讓元件具備高度封裝性的?

. 元件的獨立性
+
    * 自包含的單位 +
    每個 Angular 元件都可以看作是一個獨立的實體。 +
    元件內部包含自己的模板（HTML）、樣式（CSS）和邏輯（TypeScript）。 +
    這樣，開發者可以獨立於其他元件進行開發，測試和調試。

    * 生命週期管理 +
    Angular 通過元件的生命週期鉤子，讓開發者能夠對元件在不同階段進行操作，如初始化、更新或銷毀。

. 使用 `@Input()` 和 `@Output()` 裝飾器
+
    * 數據傳遞 +
    元件之間的數據傳遞通過 `@Input()` 裝飾器進行。 +
    父元件可以將數據傳遞給子元件，使子元件可以根據這些數據渲染自己的視圖。 +
    這種方式使得元件的使用更加靈活，同時也強化了元件之間的隔離性。
+
[source,typescript]
----
    import { Component } from "@angular/core";

    @Component({
        selector: 'app-child',
        template: `<p>子元件數據: {{ data }}</p>`
    })
    export class ChildComponent {
        @Input() data: string;  // 從父元件接收數據
    }
----
+
    * 事件發射 +
    使用 `@Output()` 裝飾器，子元件可以發出事件，告知父元件發生了某個操作。 +
    這種事件驅動的交互方式使得父子元件之間的關係保持疏鬆。
+
[source,typescript]
----
    import { Component } from "@angular/core";

    @Component({
        selector: 'app-child',
        template: `<button (click)="notifyParent()">通知父元件</button>`
    })
    export class ChildComponent {
        @Output() notify: EventEmitter<void> = new EventEmitter();

        notifyParent() {
            this.notify.emit();  // 發射事件
        }
    }
----

. 模組化架構
+
    * NgModule +
    Angular 的模組化架構使用 `@NgModule` 裝飾器，這使得開發者可以將相關的元件、指令和管道組織在一起。 +
    例如，開發者可以創建一個 `SharedModule` ，其中包含多個可以重用的元件。
+
[source,typescript]
----
@NgModule({
    declarations: [ChildComponent, AnotherComponent],
    imports: [CommonModule],
    exports: [ChildComponent]
})
export class SharedModule {}
----
+
    * 功能性模組 +
    除了 `AppModule`，開發者可以根據功能創建多個模組，使得應用更具可維護性和擴展性。 +
    這樣，開發者可以在不同的模組之間隨意重用元件，進一步提高封裝性。

. 依賴注入
+
    * 服務與依賴管理 +
    Angular 的依賴注入機制允許服務和其他依賴的管理，使得元件不需要自行創建依賴，從而減少了耦合。 +
    例如，開發者可以將 API 調用封裝在服務中，然後將該服務注入到需要的元件中。
+
[source,typescript]
----
@Injectable({
    providedIn: 'root'
})
export class ApiService {
    // ...
}

@Component({
    selector: 'app-example',
    template: `...`
})
export class ExampleComponent {
    constructor(private apiService: ApiService) {}
}
----

. 封裝 CSS
+
    * 樣式隔離 +
    Angular 提供了樣式封裝功能，讓元件的樣式不會影響到其他元件的樣式。 +
    這是通過 Shadow DOM 或者 View Encapsulation 實現。 +
    開發者可以選擇不同的樣式封裝策略，確保元件的樣式只在其範圍內有效。
+
[source,typescript]
----
@Component({
    selector: 'app-child',
    templateUrl: './child.component.html',
    styleUrls: ['./child.component.css'],
    encapsulation: ViewEncapsulation.Emulated // 預設的樣式封裝模式
})
export class ChildComponent {}
----
+
    ** 補充: link:Shadow_DOM.html[Shadow DOM]
+
    ** 補充: link:View_Encapsulation.html[View Encapsulation]


link:index.html[回首頁]