== Angular 專案結構
**Angular** 基於 **TypeScript** 開發，應用程式由 **元件 (Component)** 組成。每個元件包含 **HTML 模板**、**CSS 樣式**和帶有 `@Component()` 裝飾器的 **TypeScript 類別**。

=== 類別 (Class)
類別裡面包含了元件的相關邏輯，例如資料處理、事件處理等。 +
類別會放在 `app.component.ts` 檔案裡，而 `app` 就是元件的名稱。 +
當建立一個元件時，他會帶有 `@Component()` 裝飾器，裡面會有檔案的路徑指向，告訴Angular要去哪裡找HTML模板和CSS樣式。 +
一個元件的基本寫法如下：

[source,typescript]
----
import { Component } from "@angular/core";

@Component({
    selector: "app-item",
    // 接下來的檔案路徑會指出其它檔案在什麼位置
    templateUrl: "./item.component.html",
    styleUrls: ["./item.component.css"],
})
export class ItemComponent {
    // 程式碼寫在這裡
}
----

這個元件被稱為 `ItemComponent`，他的選擇器是 `app-item` 。 +
選擇器就像是HTML的標籤，可以把他放到其他的模板裡。 +
當瀏覽器渲染到選擇器時，就會把這個元件的HTML模板和CSS樣式一起渲染出來。

Angular 的元件具備高度封裝性，讓專案結構看起來更直覺。 而 Angular 的元件也讓專案更易於做單元測試、讓程式碼更易於解讀。

==== Angular怎麼讓元件具備高度封裝性的?

. 元件的獨立性

    * 自包含的單位 +
    每個 Angular 元件都可以看作是一個獨立的實體。 +
    元件內部包含自己的模板（HTML）、樣式（CSS）和邏輯（TypeScript）。 +
    這樣，開發者可以獨立於其他元件進行開發，測試和調試。

    * 生命週期管理 +
    Angular 通過元件的生命週期鉤子，讓開發者能夠對元件在不同階段進行操作，如初始化、更新或銷毀。

. 使用 `@Input()` 和 `@Output()` 裝飾器

    * `@Input()` 裝飾器 +
    通過 `@Input()` 裝飾器，父元件可以向子元件傳遞數據。 +
    子元件可以通過設置 `@Input()` 屬性來接收父元件傳遞的數據。

     * `@Output()` 裝飾器 +
    通過 `@Output()` 裝飾器，子元件可以向父元件發送事件。 +
    子元件可以通過 `EventEmitter` 類來發送事件，父元件可以訂閱這些事件。

=== HTML模板 (Template)

link:index.html[回首頁]